include:
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: DAST.gitlab-ci.yml

variables:
  DAST_WEBSITE: https://calebukle.com
  DAST_FULL_SCAN_ENABLED: true
  DAST_REQUEST_HEADERS: 'Cache-control: no-cache,User-Agent: Gitlab-CI;DAST/1.0'

cache:
  paths:
    - node_modules/

test:
  image: trion/ng-cli-karma
  stage: test
  environment: prod
  before_script:
    - npm install
  script:
    - npm run test:ci
  artifacts:
    paths:
      - coverage
    expire_in: 30 days

pages:
  image: alpine
  stage: deploy
  needs:
    - test
  environment: prod
  script:
    - mkdir public
    - cp -R coverage public
  artifacts:
    paths:
      - public
    expire_in: 60 days


#dependency_scanning:
#  image: docker:stable
#  variables:
#    DOCKER_DRIVER: overlay2
#  allow_failure: true
#  services:
#    - docker:stable-dind
#  script:
#    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
#    - docker run
#      --env DEP_SCAN_DISABLE_REMOTE_CHECKS="${DEP_SCAN_DISABLE_REMOTE_CHECKS:-false}"
#      --volume "$PWD:/code"
#      --volume /var/run/docker.sock:/var/run/docker.sock
#      "registry.gitlab.com/gitlab-org/security-products/dependency-scanning:$SP_VERSION" /code
#  artifacts:
#    reports:
#      dependency_scanning: gl-dependency-scanning-report.json
#
#sast:
#  image: docker:stable
#  variables:
#    DOCKER_DRIVER: overlay2
#  allow_failure: true
#  services:
#    - docker:stable-dind
#  script:
#    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
#    - docker run
#      --env SAST_CONFIDENCE_LEVEL="${SAST_CONFIDENCE_LEVEL:-3}"
#      --volume "$PWD:/code"
#      --volume /var/run/docker.sock:/var/run/docker.sock
#      "registry.gitlab.com/gitlab-org/security-products/sast:$SP_VERSION" /app/bin/run /code
#  artifacts:
#    reports:
#      sast: gl-sast-report.json
#
#
#dast:
#  image: registry.gitlab.com/gitlab-org/security-products/zaproxy
#  variables:
#    website: "https://calebukle.com"
#  allow_failure: true
#  script:
#    - mkdir /zap/wrk/
#    - /zap/zap-baseline.py -J gl-dast-report.json -t $website || true
#    - cp /zap/wrk/gl-dast-report.json .
#  artifacts:
#    reports:
#      dast: gl-dast-report.json
#
#publish:
#  image: node:8.15.0
#  stage: deploy
#  environment: prod
#  dependencies:
#    - bundle
#  only:
#    - master
#  script:
#    - npm run global add firebase-tools
#    - npm run install
#    - npm run deploy
