cache:
  paths:
    - node_modules/


include:
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: DAST.gitlab-ci.yml


dast:
  stage: dast # IMPORTANT: don't forget to add this
  variables:
    DAST_WEBSITE: "https://calebukle.com"
    CI_DEBUG_TRACE: "true"



test:
  image: trion/ng-cli-karma
  stage: test
  environment: prod
  before_script:
    - npm install
  script:
    - npm run test:ci
  coverage: /Statements.*?(\d+(?:\.\d+)?)%/
  artifacts:
    paths:
      - coverage
    expire_in: 30 days

pages:
  image: alpine
  stage: deploy
  needs:
    - test
  environment: prod
  script:
    - mkdir public
    - cp -R coverage public
  artifacts:
    paths:
      - public
    expire_in: 60 days
